App\Entity\Book:
    properties:
        title:
            - NotBlank: ~
            - Length:
                min: 2
                max: 250
                minMessage: 'Your title must be at least {{ limit }} characters long'
                maxMessage: 'Your title cannot be longer than {{ limit }} characters'
                allowEmptyString: false